<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-01-15">

<title>UFC Champ predictions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ufc_files/libs/clipboard/clipboard.min.js"></script>
<script src="ufc_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ufc_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ufc_files/libs/quarto-html/popper.min.js"></script>
<script src="ufc_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ufc_files/libs/quarto-html/anchor.min.js"></script>
<link href="ufc_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ufc_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ufc_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ufc_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ufc_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">UFC Champ predictions</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This dataset contains information on UFC fights that had a champion participating. This dataset is 4 years old so what I would like to do is create a model, perhaps a simple one, that will be used to predict championship title matches that have happened since and upcoming bouts. To challenge myself further I wil try to make <strong>USEFUL</strong> vizualizations and will be using python to throughout this project including using new packages such as matplotlib, seaborn and plotly (I have minimial experience with pandas).</p>
<p>First lets load in these packages and our <a href="https://www.kaggle.com/datasets/akouaorsot/ufc-champions-fights/data">UFC dataset</a> from kaggle and take a look at some of the first rows of the dataset</p>
<div id="4befda50" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>base_dir <span class="op">=</span> os.path.dirname(os.path.abspath(<span class="st">"__file__"</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>data_path <span class="op">=</span> os.path.join(base_dir, <span class="st">".."</span>, <span class="st">"data"</span>, <span class="st">"ufc_champs_final.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>ufc <span class="op">=</span> pd.read_csv(data_path)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, classification_report</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ufc.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Unnamed: 0 weightclass           R_fighter     B_fighter  R_odds  B_odds  \
0           0   Flyweight  Demetrious Johnson  Henry Cejudo  -470.0     375   
1           1   Flyweight  Demetrious Johnson      Ray Borg -1000.0     650   
2           2   Flyweight  Demetrious Johnson   Wilson Reis -1100.0     700   
3           3   Flyweight  Demetrious Johnson   Tim Elliott  -900.0     600   
4           4   Flyweight  Demetrious Johnson  Henry Cejudo  -340.0     280   

        R_ev   B_ev       date                      location  ...  \
0  21.276596  375.0   8/4/2018  Los Angeles, California, USA  ...   
1  10.000000  650.0  10/7/2017        Las Vegas, Nevada, USA  ...   
2   9.090909  700.0  4/15/2017    Kansas City, Missouri, USA  ...   
3  11.111111  600.0  12/3/2016        Las Vegas, Nevada, USA  ...   
4  29.411765  280.0  4/23/2016        Las Vegas, Nevada, USA  ...   

  finish_details finish_round  finish_round_time total_fight_time_secs  \
0            NaN          5.0               5:00                1500.0   
1         Armbar          5.0               3:15                1395.0   
2         Armbar          3.0               4:49                 889.0   
3            NaN          5.0               5:00                1500.0   
4          Knees          1.0               2:49                 169.0   

  r_dec_odds  b_dec_odds  r_sub_odds  b_sub_odds  r_ko_odds  b_ko_odds  
0      215.0       715.0       180.0      1845.0      300.0      800.0  
1      170.0      1800.0       180.0      1400.0      215.0     1700.0  
2      105.0      1200.0       500.0       800.0      155.0     2000.0  
3      150.0      1400.0       185.0      2000.0      259.0     1600.0  
4      109.0       400.0       410.0      2400.0      445.0     1340.0  

[5 rows x 121 columns]</code></pre>
</div>
</div>
<div id="dbb12a86" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, classification_report</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we can see there are a 121 variables so we need to consider whether there are variables that are unnecessary for our purposes such as significant strikes as we are going to use our model to try and predict future title bouts and until the bout is over we do not know these quantites. First lets take a look at the counts of NAs in each variable in descending order, this is implemented in the following code chunk:</p>
<div id="5ab0495c" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>na_counts <span class="op">=</span> ufc.isna().<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(na_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>B_Women's Featherweight_rank    771
B_Women's Flyweight_rank        762
R_Women's Flyweight_rank        760
R_Women's Featherweight_rank    755
B_Flyweight_rank                732
                               ... 
loss_dif                          0
total_round_dif                   0
total_title_bout_dif              0
ko_dif                            0
better_rank                       0
Length: 121, dtype: int64</code></pre>
</div>
</div>
<p>As we can see there are numerous variables that have considerable missing data especially these columns defining one of the fighters respective rank during the dates of the bouts which makes sense as each fighter that is not a champion at the time of the respective bout will only have 1 rank in 1 weight class (out of 12). Notice we have a weightclass column so can we collapse the ranks into 1 column that gives their rank and we already would know their weightclass from the weightclass column. Luckily I just noticed there is a column that already does this so we can drop 24 variables, but if there was no column that did this we would be able to use python’s version of pivot longer with the melt function collapsing the columns into one after filtering them with some form of regular expression.</p>
<div id="acd5f80d" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ufc_subset_drop <span class="op">=</span> ufc.<span class="bu">filter</span>(regex<span class="op">=</span><span class="st">"_rank"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ufc_subset_drop <span class="op">=</span> ufc_subset_drop.drop(columns <span class="op">=</span> [<span class="st">"B_match_weightclass_rank"</span>, <span class="st">"R_match_weightclass_rank"</span>, <span class="st">"B_Pound-for-Pound_rank"</span>, <span class="st">"better_rank"</span>, <span class="st">"R_Pound-for-Pound_rank"</span>]) </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>ufc_subset_keep <span class="op">=</span> [f <span class="cf">for</span> f <span class="kw">in</span> ufc <span class="cf">if</span> f <span class="kw">not</span> <span class="kw">in</span> ufc_subset_drop]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#With the code above we have a subset that has selected the 24 columns of interest</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a> ufc_subset <span class="op">=</span> ufc.melt(id_vars <span class="op">=</span> ufc_subset_keep,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                    value_cars <span class="op">=</span> ufc_subset_keep,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                    var_name <span class="op">=</span> <span class="st">"weight_class_rank"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                    value_name <span class="op">=</span> <span class="st">"rank"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code above is an implementation of using the melt function for the purpose stated above. Instead we can just drop the 24 variables as shown in the following code chunk. Now we have 97 variables.</p>
<div id="b59ce0a7" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ufc_subset_drop <span class="op">=</span> ufc.<span class="bu">filter</span>(regex<span class="op">=</span><span class="st">"_rank"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ufc_subset_drop <span class="op">=</span> ufc_subset_drop.drop(columns <span class="op">=</span> [<span class="st">"B_match_weightclass_rank"</span>, <span class="st">"R_match_weightclass_rank"</span>, <span class="st">"B_Pound-for-Pound_rank"</span>, <span class="st">"better_rank"</span>, <span class="st">"R_Pound-for-Pound_rank"</span>]) </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>ufc_cleaned_data <span class="op">=</span> ufc.drop(columns<span class="op">=</span> ufc_subset_drop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>97 variables is still a lot lets take a look to see if there are variables that will not be useful for out purposes, first lets take a look if there are variables that we will not be able to implement before the fight results. As we can see there are columns such as the round that the winner finished their opponent, the time of the finish, as well with the details of the finish.</p>
<div id="7285f48b" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ufc_cleaned_data <span class="op">=</span> ufc_cleaned_data.drop(columns <span class="op">=</span> [<span class="st">"total_fight_time_secs"</span>, <span class="st">"finish_round_time"</span>, <span class="st">"finish_round"</span>, <span class="st">"finish_details"</span>, <span class="st">"finish"</span>, <span class="st">"R_win_by_TKO_Doctor_Stoppage"</span>, <span class="st">"B_win_by_TKO_Doctor_Stoppage"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Another step we can take to reduce the amount of variables for our model is to drop columns that cannot be quantified or add any sort of information for our model such as the date of the event, the row id, R_ev, and B_ev. I also misunderstood a column as I believed this dataset had a column for each fighter’s ethnicity or place of birth which would be important since we have information on where the fight was held which might reveal if home-field advantage is important but turns out there is only information where the fight is held not on the individual fighter’s place of birth or ethnicity and I do not think it is feasible to add every single fighters date of birth or ethnicity so I made the decision to drop these columns as they will only add noise.</p>
<div id="fca8eaa1" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ufc_cleaned_data <span class="op">=</span> ufc_cleaned_data.drop(columns <span class="op">=</span> [<span class="st">"R_ev"</span>, <span class="st">"B_ev"</span>, <span class="st">"date"</span>, <span class="st">"Unnamed: 0"</span>, <span class="st">"empty_arena"</span>, <span class="st">"country"</span>, <span class="st">"location"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There also seems to be redundant data (multicolinearity), for example we have information on the reach of both fighters, which is most likely important, but we also have a column dedicated to telling us the reach difference so it is easy to see the redundnacy, another example is the individual weights of the fighters as they fight at the same weight class so we know they are already at the same weight. I also find it important to notice that there might be data that seems redundant but there might be good reasons to keep the variable and in this dataset it corresponds to the individual ages of the fighters and the weight difference because for example the columns that has the weight difference treats all 5 year age differences the same which is not the case in athletic sports for instance there is a big difference between a 27 year old fighting a 32 year old (both in their physical primes) and a 32 year old fighting a 37 year old (one in his prime the other years outside their prime). In the following code cell I display all variables that contain “_dif” and from there I will make the decision whether to drop the “dif” column or the corresponding columns it is related to.</p>
<div id="e10b3e82" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ufc_diff_subset <span class="op">=</span> ufc.<span class="bu">filter</span>(regex <span class="op">=</span> <span class="st">'_dif'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ufc_diff_subset.head())</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>ufc_cleaned_data <span class="op">=</span> ufc_cleaned_data.assign(sig_str_pct_diff <span class="op">=</span> ufc_cleaned_data[<span class="st">"R_avg_SIG_STR_pct"</span>] <span class="op">-</span> ufc_cleaned_data[<span class="st">"B_avg_SIG_STR_pct"</span>])</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>ufc_cleaned_data <span class="op">=</span> ufc_cleaned_data.assign(td_pct_diff <span class="op">=</span> ufc_cleaned_data[<span class="st">"R_avg_TD_pct"</span>] <span class="op">-</span> ufc_cleaned_data[<span class="st">"B_avg_TD_pct"</span>])</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>ufc_cleaned_data <span class="op">=</span> ufc_cleaned_data.drop(columns <span class="op">=</span> [<span class="st">"B_current_lose_streak"</span>, <span class="st">"R_current_lose_streak"</span>, <span class="st">"B_current_win_streak"</span>, <span class="st">"R_current_win_streak"</span>, <span class="st">"B_draw"</span>, <span class="st">"R_draw"</span>, <span class="st">"B_avg_SIG_STR_landed"</span>, <span class="st">"R_avg_SIG_STR_landed"</span>, <span class="st">"B_avg_SIG_STR_pct"</span>, <span class="st">"R_avg_SIG_STR_pct"</span>, <span class="st">"B_avg_SUB_ATT"</span>, <span class="st">"R_avg_SUB_ATT"</span>, <span class="st">"B_avg_TD_landed"</span>, <span class="st">"R_avg_TD_landed"</span>, <span class="st">"B_longest_win_streak"</span>, <span class="st">"R_longest_win_streak"</span>, <span class="st">"B_losses"</span>, <span class="st">"R_losses"</span>, <span class="st">"B_total_rounds_fought"</span>, <span class="st">"R_total_rounds_fought"</span>, <span class="st">"B_total_title_bouts"</span>, <span class="st">"R_total_title_bouts"</span>, <span class="st">"B_win_by_Decision_Majority"</span>, <span class="st">"R_win_by_Decision_Majority"</span>, <span class="st">"B_Height_cms"</span>, <span class="st">"R_Height_cms"</span>, <span class="st">"B_Reach_cms"</span>, <span class="st">"R_Reach_cms"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   lose_streak_dif  win_streak_dif  longest_win_streak_dif  win_dif  loss_dif  \
0                0             -11                      -9       -9         0   
1                0             -10                      -9       -9         0   
2                0              -8                      -8       -7         0   
3               -3             -10                      -8      -10        -2   
4                0              -5                      -5       -7         2   

   total_round_dif  total_title_bout_dif  ko_dif  sub_dif  height_dif  \
0              -43                   -12      -1       -5        2.54   
1              -40                   -12      -2       -2        2.54   
2              -36                   -11      -2       -1        2.54   
3              -35                   -10      -2       -3       10.16   
4              -38                    -9      -1       -3        2.54   

   reach_dif  age_dif  sig_str_dif  avg_sub_att_dif  avg_td_dif  
0      -5.08        0   -17.860294        -0.580882   -2.294118  
1      -7.62        7   -44.821429         0.946429   -1.348214  
2      -2.54       -2   -35.708333         0.025000    0.108333  
3       0.00        1    -7.380952         0.738095   -1.047619  
4      -5.08        0   -10.250000        -0.211538   -2.288462  </code></pre>
</div>
</div>
<p>As we can see we are now at 57 variables and I was struggling what to do with all of these betting odds and after doing some research I believe that it would be more beneficial for me to take them out as I would like to base the model off of physicial attributes and past performence, and if I keep these betting odds this model can just become a reflection of those odds so in this next code cell I will remove them.</p>
<div id="a778646b" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ufc_clean_data <span class="op">=</span> ufc_cleaned_data.drop(columns <span class="op">=</span> [<span class="st">"R_odds"</span>, <span class="st">"B_odds"</span>, <span class="st">"r_dec_odds"</span>, <span class="st">"b_dec_odds"</span>, <span class="st">"r_sub_odds"</span>, <span class="st">"b_sub_odds"</span>, <span class="st">"r_ko_odds"</span>, <span class="st">"b_ko_odds"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we are down to 49 columns and looking at a list of the columns I believe that there are no variables that need to be dropped. Something we now need to do is to decide whether or not to drop non-championship bouts so what I am going to do is create a copy of the dataset one that has only the championship fights and the other the total dataset up to this point. But first lets create a vizualization that shows us championship vs non-championship bouts.</p>
<div id="1a9fa389" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style <span class="op">=</span> <span class="st">"whitegrid"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize <span class="op">=</span> (<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> sns.countplot(data <span class="op">=</span> ufc, x <span class="op">=</span> <span class="st">"title_bout"</span>, palette <span class="op">=</span> <span class="st">"viridis"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels([<span class="st">'Non-Championship'</span>, <span class="st">'Championship'</span>])</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"non-title vs title fights"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"distribution of non-title vs title fights"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"number of fights"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\felip\AppData\Local\Temp\ipykernel_14980\1352250165.py:3: FutureWarning:



Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.


C:\Users\felip\AppData\Local\Temp\ipykernel_14980\1352250165.py:4: UserWarning:

set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="ufc_files/figure-html/cell-11-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As we can see the majority of the data is Non-Championship data so for that reason I want to create two datasets as stated prior one that has all observations and the other only championship bouts.</p>
<div id="88b51e08" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ufc_clean_total <span class="op">=</span> ufc_clean_data</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>ufc_clean_champ_only <span class="op">=</span> ufc_clean_data[ufc_clean_data[<span class="st">"title_bout"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can fit a simple model first so I would like to start with a logistic regression model in which we first have to transform our variable that we are trying to predict (Winner) into 1s and 0s from “Red” and “Blue” respectfully. Since we are using a logistic regression model we can only use numeric predictors and cannot have and NaNs in the data set so we need to prep our data.</p>
<div id="adb50c47" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we create a copy of the cleaned dataset</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>ufc_clean_log <span class="op">=</span> ufc_clean_champ_only.copy() </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Here we conver our target variable into 1s and 0s</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>ufc_clean_log[<span class="st">'target'</span>] <span class="op">=</span> ufc_clean_log[<span class="st">'Winner'</span>].<span class="bu">map</span>({<span class="st">'Red'</span>: <span class="dv">1</span>, <span class="st">'Blue'</span>: <span class="dv">0</span>})</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Here we extract only numeric columns</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>features_log <span class="op">=</span> ufc_clean_log.select_dtypes(include<span class="op">=</span>[<span class="st">'number'</span>])</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Here we filter so columns have no missing values phfilll check run head on this</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>features_log <span class="op">=</span> [col <span class="cf">for</span> col <span class="kw">in</span> features_log.columns </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> ufc_clean_log[col].isna().<span class="bu">sum</span>() <span class="op">==</span> <span class="dv">0</span> <span class="kw">and</span> col <span class="op">!=</span> <span class="st">'target'</span>]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>model_df <span class="op">=</span> ufc_clean_log[features_log <span class="op">+</span> [<span class="st">'target'</span>]].dropna()</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Here we split the data into predictors and our target variable</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> model_df[features_log]</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> model_df[<span class="st">'target'</span>]</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Here we split the data and fit the logistic regression model on the training set</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>x_train, x_test, y_train, y_test <span class="op">=</span> train_test_split(x, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>model_fit <span class="op">=</span> LogisticRegression(max_iter<span class="op">=</span><span class="dv">1000</span>) </span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>model_fit.fit(x_train, y_train)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co">#here we test the model on the test set (unseen data)</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>y_preds <span class="op">=</span> model_fit.predict(x_test)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(accuracy_score(y_test, y_preds))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.7068965517241379</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning:

lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
</code></pre>
</div>
</div>
<p>Lets see how our model performs on some championship bouts that have happened since the last update of this dataset. We have to make a new observation for the bout in question and use our model to predict the outcome. Since it would be very tedious to get every stat needed for a new observation I decided to use AI to retrieve them. This new observation is a fight that happened Jan 24 in which Gaethje won.</p>
<div id="b13a3f33" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating the stats for Gaethje (Red) vs Pimblett (Blue)</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>new_fight_stats <span class="op">=</span> {</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'no_of_rounds'</span>: [<span class="dv">5</span>],</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Split'</span>: [<span class="dv">0</span>],</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Unanimous'</span>: [<span class="dv">6</span>],</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_KO/TKO'</span>: [<span class="dv">7</span>],</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Submission'</span>: [<span class="dv">10</span>],</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_wins'</span>: [<span class="dv">23</span>],</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_Weight_lbs'</span>: [<span class="dv">155</span>],</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Split'</span>: [<span class="dv">1</span>],</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Unanimous'</span>: [<span class="dv">5</span>],</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_KO/TKO'</span>: [<span class="dv">20</span>],</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Submission'</span>: [<span class="dv">1</span>],</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_wins'</span>: [<span class="dv">27</span>],</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_Weight_lbs'</span>: [<span class="dv">155</span>],</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_age'</span>: [<span class="dv">37</span>],</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_age'</span>: [<span class="dv">31</span>],</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'lose_streak_dif'</span>: [<span class="dv">0</span>], <span class="co"># Both coming off wins</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_streak_dif'</span>: [<span class="op">-</span><span class="dv">6</span>], <span class="co"># Paddy had a longer streak (7 vs 1)</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'longest_win_streak_dif'</span>: [<span class="dv">2</span>], <span class="co"># Gaethje's peak vs Paddy's</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_dif'</span>: [<span class="dv">4</span>],</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'loss_dif'</span>: [<span class="dv">1</span>],</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_round_dif'</span>: [<span class="dv">30</span>], <span class="co"># Gaethje has much more cage time</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_title_bout_dif'</span>: [<span class="dv">6</span>], <span class="co"># Paddy has never been in a UFC title bout</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ko_dif'</span>: [<span class="dv">13</span>],</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sub_dif'</span>: [<span class="op">-</span><span class="dv">9</span>],</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'height_dif'</span>: [<span class="dv">1</span>], <span class="co"># 5'11 vs 5'10</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reach_dif'</span>: [<span class="op">-</span><span class="dv">3</span>], <span class="co"># Paddy has a reach advantage (73 vs 70)</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">'age_dif'</span>: [<span class="dv">6</span>],</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_str_dif'</span>: [<span class="fl">1.4</span>], <span class="co"># 6.59 vs 5.19</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_sub_att_dif'</span>: [<span class="op">-</span><span class="fl">1.7</span>],</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_td_dif'</span>: [<span class="op">-</span><span class="fl">0.86</span>],</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'constant_1'</span>: [<span class="dv">1</span>]</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the observation</span></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>X_new <span class="op">=</span> pd.DataFrame(new_fight_stats)</span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a><span class="co"># --- THE PREDICTION ---</span></span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Who does the model pick?</span></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a>fight_prediction <span class="op">=</span> model_fit.predict(X_new)</span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>winner_label <span class="op">=</span> <span class="st">"RED (Gaethje)"</span> <span class="cf">if</span> fight_prediction[<span class="dv">0</span>] <span class="op">==</span> <span class="dv">1</span> <span class="cf">else</span> <span class="st">"BLUE (Pimblett)"</span></span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. How confident is it?</span></span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span> model_fit.predict_proba(X_new)</span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a>confidence <span class="op">=</span> probs[<span class="dv">0</span>][<span class="dv">1</span>] <span class="cf">if</span> fight_prediction[<span class="dv">0</span>] <span class="op">==</span> <span class="dv">1</span> <span class="cf">else</span> probs[<span class="dv">0</span>][<span class="dv">0</span>]</span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Winner: </span><span class="sc">{</span>winner_label<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Model Confidence: </span><span class="sc">{</span>confidence<span class="sc">:.2%}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Winner: RED (Gaethje)
Model Confidence: 100.00%</code></pre>
</div>
</div>
<p>Our model was right!!! lets try another and I am feeling like our model is performing a little too good lets look at a fight considered the greatest upset in UFC history Adesanya vs.&nbsp;Strickland (Adesanya was a heavy favorite)</p>
<div id="4409e14c" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Stats for Sean Strickland (Red) vs Israel Adesanya (Blue) - UFC 293</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>strickland_vs_izzy <span class="op">=</span> {</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'no_of_rounds'</span>: [<span class="dv">5</span>],</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Split'</span>: [<span class="dv">0</span>],</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Unanimous'</span>: [<span class="dv">6</span>],</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_KO/TKO'</span>: [<span class="dv">15</span>],</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Submission'</span>: [<span class="dv">0</span>],</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_wins'</span>: [<span class="dv">24</span>],</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_Weight_lbs'</span>: [<span class="dv">185</span>],</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Split'</span>: [<span class="dv">2</span>],</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Unanimous'</span>: [<span class="dv">10</span>],</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_KO/TKO'</span>: [<span class="dv">11</span>],</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Submission'</span>: [<span class="dv">4</span>],</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_wins'</span>: [<span class="dv">27</span>],</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_Weight_lbs'</span>: [<span class="dv">185</span>],</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_age'</span>: [<span class="dv">32</span>],</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_age'</span>: [<span class="dv">34</span>],</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'lose_streak_dif'</span>: [<span class="dv">0</span>],</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_streak_dif'</span>: [<span class="dv">1</span>],   <span class="co"># Strickland was on 2-win streak, Izzy on 1</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'longest_win_streak_dif'</span>: [<span class="op">-</span><span class="dv">1</span>], </span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_dif'</span>: [<span class="dv">3</span>],</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'loss_dif'</span>: [<span class="dv">3</span>],         <span class="co"># Strickland had 5 losses, Izzy had 2</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_round_dif'</span>: [<span class="dv">8</span>],  <span class="co"># Strickland had more total rounds in MMA</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_title_bout_dif'</span>: [<span class="op">-</span><span class="dv">10</span>], <span class="co"># Huge gap: Izzy had 10 title bouts, Sean had 0</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ko_dif'</span>: [<span class="op">-</span><span class="dv">4</span>],</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sub_dif'</span>: [<span class="dv">4</span>],</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'height_dif'</span>: [<span class="op">-</span><span class="dv">3</span>],      <span class="co"># 6'1 vs 6'4</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reach_dif'</span>: [<span class="op">-</span><span class="dv">4</span>],       <span class="co"># 76" vs 80"</span></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">'age_dif'</span>: [<span class="op">-</span><span class="dv">2</span>],</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_str_dif'</span>: [<span class="fl">1.92</span>],   <span class="co"># 5.86 landed/min vs 3.94 landed/min</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_sub_att_dif'</span>: [<span class="fl">0.2</span>],</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_td_dif'</span>: [<span class="fl">0.94</span>],    <span class="co"># 1.00 vs 0.06</span></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'constant_1'</span>: [<span class="dv">1</span>]</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>X_strickland <span class="op">=</span> pd.DataFrame(strickland_vs_izzy)</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the prediction</span></span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>prob <span class="op">=</span> model_fit.predict_proba(X_strickland)</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Strickland Win Probability: </span><span class="sc">{</span>prob[<span class="dv">0</span>][<span class="dv">1</span>]<span class="sc">:.2%}</span><span class="ss">"</span>)</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Adesanya Win Probability: </span><span class="sc">{</span>prob[<span class="dv">0</span>][<span class="dv">0</span>]<span class="sc">:.2%}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Strickland Win Probability: 0.53%
Adesanya Win Probability: 99.47%</code></pre>
</div>
</div>
<p>As we can see our model predicted that there was over a 99% chance that Adesanya won which shows why this was such a great upset. It displays how it is hard to quantify a wildcard aspect to bouts.</p>
<p>Lets check a toss up fight Strickland vs Du Plessis(odds around -115 and -105)</p>
<div id="83face5e" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Stats for Sean Strickland (Red) vs Dricus Du Plessis (Blue) - UFC 297</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>strickland_vs_dricus <span class="op">=</span> {</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'no_of_rounds'</span>: [<span class="dv">5</span>],</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Split'</span>: [<span class="dv">0</span>],</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Unanimous'</span>: [<span class="dv">0</span>],</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_KO/TKO'</span>: [<span class="dv">19</span>], </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Submission'</span>: [<span class="dv">1</span>],</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_wins'</span>: [<span class="dv">20</span>],</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_Weight_lbs'</span>: [<span class="dv">185</span>],</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Split'</span>: [<span class="dv">2</span>],</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Unanimous'</span>: [<span class="dv">10</span>],</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_KO/TKO'</span>: [<span class="dv">11</span>],</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Submission'</span>: [<span class="dv">4</span>],</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_wins'</span>: [<span class="dv">28</span>],</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_Weight_lbs'</span>: [<span class="dv">185</span>],</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_age'</span>: [<span class="dv">32</span>],</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_age'</span>: [<span class="dv">30</span>],</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'lose_streak_dif'</span>: [<span class="dv">0</span>],</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_streak_dif'</span>: [<span class="op">-</span><span class="dv">8</span>], <span class="co"># Dricus had a massive 9-fight win streak</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'longest_win_streak_dif'</span>: [<span class="op">-</span><span class="dv">3</span>], </span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_dif'</span>: [<span class="dv">8</span>],</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'loss_dif'</span>: [<span class="dv">3</span>], <span class="co"># Strickland had more experience but more losses</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_round_dif'</span>: [<span class="dv">24</span>], </span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_title_bout_dif'</span>: [<span class="dv">1</span>], <span class="co"># Strickland was the champ, Dricus's first title bout</span></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ko_dif'</span>: [<span class="op">-</span><span class="dv">8</span>],</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sub_dif'</span>: [<span class="dv">3</span>],</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'height_dif'</span>: [<span class="dv">1</span>], <span class="co"># 6'1" vs 6'0"</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reach_dif'</span>: [<span class="dv">0</span>], <span class="co"># Both have a 76" reach</span></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">'age_dif'</span>: [<span class="dv">2</span>],</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_str_dif'</span>: [<span class="op">-</span><span class="fl">0.87</span>], <span class="co"># Du Plessis actually had higher volume (6.95 vs 6.08)</span></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_sub_att_dif'</span>: [<span class="op">-</span><span class="fl">0.8</span>],</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_td_dif'</span>: [<span class="op">-</span><span class="fl">2.72</span>], <span class="co"># Dricus is a much heavier grappler (3.72 vs 1.00)</span></span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'constant_1'</span>: [<span class="dv">1</span>]</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>X_tossup <span class="op">=</span> pd.DataFrame(strickland_vs_dricus)</span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict!</span></span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>prob <span class="op">=</span> model_fit.predict_proba(X_tossup)</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>winner <span class="op">=</span> <span class="st">"STRICKLAND (Red)"</span> <span class="cf">if</span> prob[<span class="dv">0</span>][<span class="dv">1</span>] <span class="op">&gt;</span> <span class="fl">0.5</span> <span class="cf">else</span> <span class="st">"DU PLESSIS (Blue)"</span></span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Winner: </span><span class="sc">{</span>winner<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Confidence: </span><span class="sc">{</span><span class="bu">max</span>(prob[<span class="dv">0</span>])<span class="sc">:.2%}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Winner: DU PLESSIS (Blue)
Confidence: 100.00%</code></pre>
</div>
</div>
<p>This was a controversial win but the model predicted it right, to wrap this up lets check the prediction for this weekend’s championship bout Volkanovski vs Lopes</p>
<div id="171b8044" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Stats for Alexander Volkanovski (Red) vs Diego Lopes (Blue) - UFC 325</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>volk_vs_lopes_rematch <span class="op">=</span> {</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'no_of_rounds'</span>: [<span class="dv">5</span>],</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Split'</span>: [<span class="dv">0</span>],</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Decision_Unanimous'</span>: [<span class="dv">3</span>],</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_KO/TKO'</span>: [<span class="dv">3</span>],   <span class="co"># Includes recent win over Jean Silva</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_win_by_Submission'</span>: [<span class="dv">1</span>],</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_wins'</span>: [<span class="dv">27</span>],</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_Weight_lbs'</span>: [<span class="dv">145</span>],</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Split'</span>: [<span class="dv">1</span>],</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Decision_Unanimous'</span>: [<span class="dv">11</span>],</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_KO/TKO'</span>: [<span class="dv">13</span>],</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_win_by_Submission'</span>: [<span class="dv">3</span>],</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_wins'</span>: [<span class="dv">27</span>],</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_Weight_lbs'</span>: [<span class="dv">145</span>],</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R_age'</span>: [<span class="dv">37</span>],</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'B_age'</span>: [<span class="dv">31</span>],</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'lose_streak_dif'</span>: [<span class="dv">0</span>],</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_streak_dif'</span>: [<span class="op">-</span><span class="dv">1</span>], <span class="co"># Lopes is on a 1-win streak, Volk technically has 1 win (their last fight)</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'longest_win_streak_dif'</span>: [<span class="dv">10</span>], <span class="co"># Volk's legendary 12-fight UFC streak</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'win_dif'</span>: [<span class="dv">0</span>], <span class="co"># Both sit at 27 pro wins</span></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'loss_dif'</span>: [<span class="op">-</span><span class="dv">3</span>], <span class="co"># Volk has 4 losses, Lopes has 7</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_round_dif'</span>: [<span class="dv">25</span>], <span class="co"># Volk has far more 5-round experience</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'total_title_bout_dif'</span>: [<span class="dv">14</span>], <span class="co"># Volk has 15 title fights, Lopes has 1</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ko_dif'</span>: [<span class="dv">10</span>],</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sub_dif'</span>: [<span class="dv">2</span>],</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'height_dif'</span>: [<span class="op">-</span><span class="dv">5</span>], <span class="co"># 5'6" vs 5'11" (Huge height gap)</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reach_dif'</span>: [<span class="op">-</span><span class="dv">1</span>], <span class="co"># 71" vs 72"</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">'age_dif'</span>: [<span class="dv">6</span>],</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_str_dif'</span>: [<span class="fl">2.08</span>], <span class="co"># 6.18 vs 4.10 (Landed per minute)</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_sub_att_dif'</span>: [<span class="op">-</span><span class="fl">1.5</span>],</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'avg_td_dif'</span>: [<span class="fl">0.88</span>], <span class="co"># 1.67 vs 0.79 (Takedowns per 15 min)</span></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'constant_1'</span>: [<span class="dv">1</span>]</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>X_rematch <span class="op">=</span> pd.DataFrame(volk_vs_lopes_rematch)</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the prediction</span></span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>prediction <span class="op">=</span> model_fit.predict(X_rematch)</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span> model_fit.predict_proba(X_rematch)</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>winner <span class="op">=</span> <span class="st">"VOLKANOVSKI (Red)"</span> <span class="cf">if</span> prediction[<span class="dv">0</span>] <span class="op">==</span> <span class="dv">1</span> <span class="cf">else</span> <span class="st">"LOPES (Blue)"</span></span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predicted Winner: </span><span class="sc">{</span>winner<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Confidence: </span><span class="sc">{</span>probs[<span class="dv">0</span>][prediction[<span class="dv">0</span>]]<span class="sc">:.2%}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Winner: VOLKANOVSKI (Red)
Confidence: 100.00%</code></pre>
</div>
</div>
<p>I’m a diego lopes fan so now I hope my model is wrong on this one, but the predicted outcome is similar to what the mainstream opinion is as Volkanovski is considered one of the greatest to ever do it and very experienced.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>